class CameraCreateLabels:
   CommandNameLabel="CameraCreate"
   NewIdLabel="NewId"
class CameraGetLabels:
   CommandNameLabel="CameraGet"
   NearLabel="Near"
   FarLabel="Far"
   EyePositionLabel="EyePosition"
   TargetPositionLabel="TargetPosition"
   UpVectorLabel="UpVector"
   ProjectionMatrixLabel="ProjectionMatrix"
   RotationMatrixLabel="RotationMatrix"
class CameraLabels:
   CameraFitCommandLabel="CameraFit"
   CameraXYCommandLabel="CameraXY"
   CameraYZCommandLabel="CameraYZ"
   CameraZXCommandLabel="CameraZX"
   CameraRotateCommandLabel="CameraRotate"
   MatrixLabel="Matrix"
   TranslateLabel="Translate"
   CameraTranslateCommandLabel="CameraTranslate"
   CameraZoomCommandLabel="CameraZoom"
   ZoomRatioLabel="Ratio"
class CameraSetLabels:
   CommandLabel="CameraSet"
   NearLabel="Near"
   FarLabel="Far"
   EyePositionLabel="EyePosition"
   TargetPositionLabel="TargetPosition"
   UpVector="UpVector"
class ClearLabels:
   CommandNameLabel="ClearCommand"
   LayerLabel="Layer"
class DeleteLabels:
   CommandNameLabel="DeleteCommand"
   IdLabel="Id"
   IsItemLabel="IsItem"
class FileExportLabels:
   FileExportCommandLabel="FileExport"
   FilePathLabel="FilePath"
class FileImportLabels:
   FileImportCommandLabel="FileImport"
   FilePathLabel="FilePath"
   IsOkLabel="IsOk"
   NewIdLabel="NewId"
   STLFileImportCommandLabel="STLFileImport"
class GetLabels:
   PositionLabel="Position"
   SceneCountLabel="SceneCount"
   SceneListIdsLabel="SceneListIds"
   MaterialNameLabel="MaterialName"
class GetMatrixLabels:
   CommandLabel="SetMatrix"
   IdLabel="Id"
   MatrixLabel="Matrix"
class LightCreateLabels:
   CommandNameLabel="LightCreate"
   PositionLabel="Position"
   AmbientLabel="Ambient"
   DiffuseLabel="Diffuse"
   SpecularLabel="Specular"
   NameLabel="Name"
   NewIdLabel="NewId"
class LightGetLabels:
   CommandNameLabel="LightGet"
   IdLabel="Id"
   PositionLabel="Position"
   AmbientLabel="Ambient"
   DiffuseLabel="Diffuse"
   SpecularLabel="Specular"
   NameLabel="Name"
class LightSetLabels:
   CommandNameLabel="LightSet"
   IdLabel="Id"
   PositionLabel="Position"
   AmbientLabel="Ambient"
   DiffuseLabel="Diffuse"
   SpecularLabel="Specular"
   NameLabel="Name"
class MaterialCreateLabels:
   CommandNameLabel="MaterialCreate"
   AmbientLabel="Ambient"
   DiffuseLabel="Diffuse"
   SpecularLabel="Specular"
   ShininessLabel="Shininess"
   AmbientTextureNameLabel="AmbientTextureName"
   DiffuseTextureNameLabel="DiffuseTextureName"
   SpecularTextureNameLabel="SpecularTextureName"
   NameLabel="Name"
   NewIdLabel="NewId"
class MaterialGetLabels:
   CommandNameLabel="MaterialGet"
   IdLabel="Id"
   AmbientLabel="Ambient"
   DiffuseLabel="Diffuse"
   SpecularLabel="Specular"
   ShininessLabel="Shininess"
   TextureNameLabel="TextureName"
   NameLabel="Name"
class MaterialSetLabels:
   CommandNameLabel="MaterialSet"
   IdLabel="Id"
   AmbientLabel="Ambient"
   DiffuseLabel="Diffuse"
   SpecularLabel="Specular"
   ShininessLabel="Shininess"
   TextureNameLabel="TextureName"
   NameLabel="Name"
class MockLabels:
   MockCommandLabel="Mock"
class NewLabels:
   CommandNameLabel="NewCommand"
class OBJFileExportLabels:
   CommandNameLabel="OBJFileExport"
   FilePathLabel="FilePath"
   IdsLabel="Ids"
class OBJFileImportLabels:
   CommandNameLabel="OBJFileImport"
   FilePathLabel="FilePath"
   NewIdLabel="NewId"
class ParticleSystemCreateLabels:
   ParticleSystemAddLabel="ParticleSystemAdd"
   PositionsLabel="Positions"
   PointSizeLabel="PointSize"
   ColorLabel="Color"
   NameLabel="Name"
   LayerLabel="Layer"
   NewIdLabel="NewId"
class ParticleSystemGetLabels:
   CommandNameLabel="ParticleSystemGet"
   PSIdLabel="PSId"
   LayerLabel="Layer"
   PositionsLabel="Positions"
   PointSizeLabel="PointSize"
   ColorLabel="Color"
   NameLabel="Name"
class PCDFileExportLabels:
   CommandNameLabel="PCDFileExport"
   FilePathLabel="FilePath"
   IdsLabel="Ids"
   IsBinaryLabel="IsBinary"
class PCDFileImportLabels:
   CommandNameLabel="PCDFileImport"
   FilePathLabel="FilePath"
   NewIdLabel="NewId"
class PickLabels:
   PickCommandLabel="Pick"
   PositionLabel="Position"
   ParentIdLabel="ParentId"
   ChildIdLabel="ChildId"
class PolygonMeshAddFacesLabels:
   CommandNameLabel="PolygonMeshAddFaces"
   PolygonMeshIdLabel="PolygonMeshId"
   VertexIdsLabel="VertexIds"
class PolygonMeshAddVerticesLabels:
   CommandNameLabel="PolygonMeshAddVertices"
   PolygonMeshIdLabel="PolygonMeshId"
   PositionIdsLabel="PositionIds"
   NormalIdsLabel="NormalIds"
   TexCoordIdsLabel="TexCoordIds"
class PolygonMeshCreateLabels:
   CommandNameLabel="PolygonMeshCreate"
   PositionsLabel="Positions"
   NormalsLabel="Normals"
   TexCoordsLabel="TexCoords"
   VerticesLabel="Vertices"
   FacesLabel="Faces"
   NameLabel="Name"
   LayerLabel="Layer"
   NewIdLabel="NewId"
class PresenterSetLabels:
   CommandNameLabel="PresenterSet"
   IdLabel="Id"
   PresenterNameLabel="PresenterName"
class SceneGetLabels:
   CommandLabel="SceneGet"
   IdLabel="Id"
   BoundingBoxLabel="BoundingBox"
   IsPickableLabel="IsPickable"
   IsVisibleLabel="IsVisible"
   NameLabel="Name"
   TypeNameLabel="TypeName"
class SceneSetLabels:
   CommandNameLabel="SceneSet"
   IdLabel="Id"
   NameLabel="Name"
class ShaderBuildLabels:
   CommandNameLabel="ShaderBuild"
   IdLabel="Id"
class ShaderSendLabels:
   CommandNameLabel="ShaderSend"
   IdLabel="Id"
class ShapeSelectLabels:
   CommandNameLabel="ShapeSelectCommand"
   ShapeIdLabel="ShapeId"
class SolidCreateLabels:
   ParticleSystemAddLabel="SolidCreate"
   BoxLabel="Box"
   ColorLabel="Color"
   NameLabel="Name"
   LayerLabel="Layer"
   NewIdLabel="NewId"
class STLFileExportLabels:
   CommandNameLabel="STLFileExport"
   FilePathLabel="FilePath"
   IdsLabel="Ids"
   IsBinaryLabel="IsBinary"
class STLFileImportLabels:
   CommandNameLabel="STLFileImport"
   FilePathLabel="FilePath"
   NewIdLabel="NewId"
class TextureCreateLabels:
   CommandNameLabel="TextureCreate"
   FilePathLabel="FilePath"
   NameLabel="Name"
   NewIdLabel="NewId"
class TextureSetLabels:
   CommandNameLabel="TextureSet"
   IdLabel="Id"
   FilePathLabel="FilePath"
   IsOkLabel="IsOk"
class TransformLabels:
   TransformCommandLabel="Transform"
   IdLabel="Id"
   MatrixLabel="Matrix"
class TrimLabels:
   TrimCommandLabel="Trim"
   ShapeIdLabel="ShapeId"
   SpaceLabel="Space"
   NewIdLabel="NewId"
class WireFrameCreateLabels:
   WireFrameAddLabel="WireFrameAdd"
   PositionsLabel="Positions"
   EdgesLabel="Edges"
   LineWidthLabel="LineWidth"
   ColorLabel="Color"
   NameLabel="Name"
   LayerLabel="Layer"
   NewIdLabel="NewId"
