class MeshToPSLabels:
   CommandNameLabel="MeshToPS"
   PolygonMeshIdLabel="PolygonMeshId"
   DivideLengthLabel="DivideLength"
   ParticleSystemIdLabel="ParticleSystemId"
class MeshToVoxelLabels:
   CommandNameLabel="MeshToVoxelCommand"
   PolygonMeshIdLabel="PolygonMeshId"
   VoxelIdLabel="VoxelId"
   DivideLengthLabel="DivideLength"
class SparseVolumeNodeSetLabels:
   CommandNameLabel="SparseVolumeNodeSet"
   SparseVolumeIdLabel="SparseVolumeId"
   IndicesXLabel="IndicesX"
   IndicesYLabel="IndicesY"
   IndicesZLabel="IndicesZ"
   ValuesLabel="Values"
class SparseVolumeSceneCreateLabels:
   CommandNameLabel="SparseVolumeSceneCreate"
   ResolutionXLabel="ResolutionX"
   ResolutionYLabel="ResolutionY"
   ResolutionZLabel="ResolutionZ"
   BoundingBoxLabel="BoundingBox"
   NameLabel="Name"
   LayerLabel="Layer"
   NewIdLabel="NewId"
class VoxelGetLabels:
   CommandNameLabel="VoxelGet"
   VoxelIdLabel="VoxelId"
   ResolutionXLabel="ResX"
   ResolutionYLabel="ResY"
   ResolutionZLabel="ResZ"
   ValuesLabel="Values"
class VoxelizerLabels:
   CommandNameLabel="VoxelizerCommand"
   MeshIdLabel="MeshId"
   VoxelIdLabel="VoxelId"
   DivideLengthLabel="DivideLength"
class VoxelSceneCreateLabels:
   CommandNameLabel="VoxelSceneCreate"
   ResolutionXLabel="ResolutionX"
   ResolutionYLabel="ResolutionY"
   ResolutionZLabel="ResolutionZ"
   BoundingBoxLabel="BoundingBox"
   NameLabel="Name"
   LayerLabel="Layer"
   NewIdLabel="NewId"
class VoxelSetLabels:
   CommandNameLabel="VoxelNodeSet"
   VoxelIdLabel="VoxelId"
   IndicesXLabel="IndicesX"
   IndicesYLabel="IndicesY"
   IndicesZLabel="IndicesZ"
   ValuesLabel="Values"
class VoxelToPSLabels:
   CommandNameLabel="VoxelToPSCommand"
   VoxelIdLabel="VoxelId"
   PSIdLabel="PSId"
